name: OramiPlugs
version: 1.0.1
main: fr.niastiik.oramiplugs.Main
api-version: 1.21
author: Niastiik
description: Plugin de base OramiPlugs
commands:
  heal:
    description: "Permet de remplire la barre de vie"
    permission: oramiplugs.heal
    usage: "§7[§c§lOramiPlugs§7] §e/heal [Player]"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  feed:
    description: "Permet de remplire la barre de nourriture"
    permission: oramiplugs.feed
    usage: "§7[§c§lOramiPlugs§7] §e/feed [Player]"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  day:
    description: "Permet de mettre le jour"
    permission: oramiplugs.day
    aliases:
    - jour
    usage: "§7[§c§lOramiPlugs§7] §e/day"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  night:
    description: "Permet de mettre la nuit"
    permission: oramiplugs.night
    aliases:
    - nuit
    usage: "§7[§c§lOramiPlugs§7] §e/night"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  broadcast:
    description: "Permet de faire une annonce"
    permission: oramiplugs.broadcast
    aliases:
    - bc
    - alert
    - brc
    usage: "§7[§c§lOramiPlugs§7] §e/broadcast <Message>"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  information:
    description: "Permet de donner les infos d'un joueur"
    permission: oramiplugs.info
    aliases:
    - i
    - info
    usage: "§7[§c§lOramiPlugs§7] §e/information <Player>"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  suicide:
    description: "Permet de ce suicider"
    usage: "§7[§c§lOramiPlugs§7] §e/suicide"
  sun:
    description: P"ermet de mettre un beau soleil"
    permission: oramiplugs.sun
    aliases:
    - soleil
    usage: "§7[§c§lOramiPlugs§7] §e/sun"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  rain:
    description: "Permet de mettre un belle pluie"
    permission: oramiplugs.rain
    aliases:
    - pluie
    usage: "§7[§c§lOramiPlugs§7] §e/rain"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  clear:
    description: "Permet de supprimer son inventaire ou celui d'un autre joueur"
    permission: oramiplugs.clear
    usage: "§7[§c§lOramiPlugs§7] §e/clear [Player]"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  kill:
    description: "Permet de tuer un joueur"
    permission: oramiplugs.kill
    usage: "§7[§c§lOramiPlugs§7] §e/kill <Player>"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  msg:
    description: "Permet de communiquer entre deux joueur sans que d'autre personne ne le vois"
    aliases:
    - m
    - message
    usage: "§7[§c§lOramiPlugs§7] §e/msg <Player> <Message>"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  fly:
    description: "Permet de s'envoler"
    permission: ormamiplugs.fly
    aliases:
    - flying
    - f
    usage: "§7[§c§lOramiPlugs§7] §e/fly"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  inventory:
    description: P"ermet de voir l'inventaire d'un joueur"
    permission: oramiplugs.inventory
    aliases:
    - invsee
    - inventaire
    - inv
    usage: "§7[§c§lOramiPlugs§7] §e/inventory <Player>"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  enderchest:
    description: "Permet de voir son enderchest ou celui d'un autre joueur"
    permission: oramiplugs.enderchest
    aliases:
    - ec
    usage: "§7[§c§lOramiPlugs§7] §e/enderchest [Player]"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  staff:
    description: "Permet de passer en mode staff"
    permission: oramiplugs.staff
    aliases:
    - mod
    usage: "§7[§c§lOramiPlugs§7] §e/staff"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  gamemode:
    description: "Permet de changer de gamemode"
    permission: oramiplugs.gamemode
    aliases:
    - gm
    usage: "§7[§c§lOramiPlugs§7] §e/gamemode <Mode> [Player]"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  vanish:
    description: éPermet de se faire cacher des autres joueur"
    permission: oramiplugs.vanish
    aliases:
    - v
    usage: "§7[§c§lOramiPlugs§7] §e/vanish"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  freeze:
    description: "Permet de freeze un joueur"
    permission: oramiplugs.freeze
    usage: "§7[§c§lOramiPlugs§7] §e/freeze <Player>"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  report:
    description: "Permet de signaler un joueur"
    aliases:
    - signale
    usage: "§7[§c§lOramiPlugs§7] §e/report <Player>"
  kick:
    description: "Permet d'expulser un joueur"
    permission: oramiplugs.kick
    usage: "§7[§c§lOramiPlugs§7] §e/kick <Player> <Message>"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  god:
    description: "Permet de devenir invincible ou de rendre un joueur invincible"
    permission: oramiplugs.god
    usage: "§7[§c§lOramiPlugs§7] §e/god [Player]"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  randomtp:
    description: "Permet de se téléporte aleatoirement dans la map"
    usage: "§7[§c§lOramiPlugs§7] §e/randomtp"
    aliases:
    - rtp
  tp:
    description: "Permet de se teleporte à un autre joueur"
    permission: oramiplugs.tp
    usage: "§7[§c§lOramiPlugs§7] §e/tp <Player>"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  craft:
    description: "Permet d'ouvrir une table de craft"
    permission: oramiplugs.craft
    usage: "§7[§c§lOramiPlugs§7] §e/craft"
    permission-message: "§7[§c§lOramiPlugs§7] §cVous n'avez pas la permission d'utiliser cette commande."
  spawn:
    description: "Permet de se téléporter au spawn de la map"
    usage: "§7[§c§lOramiPlugs§7] §e/spawn"
  trade:
    description: "Permet de faire des échanges de stuff"
    usage: "§7[§c§lOramiPlugs§7] §e/trade"
  repair:
    description: "Permet de réparer son stuff"
    usage: "§7[§c§lOramiPlugs§7] §e/repair [all]"